#!/usr/bin/sh

######################################
## /usr/local/bin/hdmi_unplug
######################################
X_USER=georgem
export DISPLAY=:0
export XAUTHORITY=/home/$X_USER/.Xauthority
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
HDMI_STATUS=$(cat /sys/devices/pci0000:00/0000:00:08.1/0000:05:00.0/drm/card0/card0-HDMI-A-1/status)
LID_STATE=$(cat /proc/acpi/button/lid/LID/state | cut -d':' -f2 | tr -d ' ')

connect()
{   
    case $1 in
        "open")
            # I don't want automatic desktop extension on the output.
            # I prefer manual switching to the desired mode.
            xrandr --output eDP --primary --auto --output HDMI-A-0 --off
            ;;
        "closed")
            xrandr --output eDP --off --output HDMI-A-0 --primary --auto
            if [ ! -z "$(pgrep -fa Xsession | grep qtile)" ]
            then
                qtile-cmd -o cmd -f restart 2> /dev/null
            fi
            if [ ! -z "$(pgrep -fa Xsession | grep xmonad)" ]
            then
                echo " " > /tmp/displaymode #to display icons on Xmobar
                echo "HDMI" >> /tmp/displaymode
                xmonad --restart
            fi
            feh --bg-fill ~/Pictures/Wallpapers/Rei.png
            ;;
    esac
}

disconnect(){
    xrandr --output eDP --primary --auto --output HDMI-A-0 --off
    if [ ! -z "$(pgrep -fa Xsession | grep qtile)" ]
    then
        qtile-cmd -o cmd -f restart 2> /dev/null
    fi
    if [ ! -z "$(pgrep -fa Xsession | grep xmonad)" ]
    then
        echo " " > /tmp/displaymode # to display icons on Xmobar
        echo "default" >> /tmp/displaymode
        xmonad --restart
    fi
    feh --bg-fill ~/Pictures/Wallpapers/Rei.png
}

if [ "${HDMI_STATUS}" = "disconnected" ]; then
    disconnect
elif [ "${HDMI_STATUS}" = "connected" ]; then
    connect "${LID_STATE}"
fi

exit

