#!/usr/bin/env bash

##  use your current screen as screenlock
#PICTURE=/tmp/i3lock.png
#SCREENSHOT="scrot $PICTURE"

#BLUR="5x4"

# $SCREENSHOT
# convert $PICTURE -blur $BLUR $PICTURE
# i3lock -i $PICTURE

# rm $PICTURE

## use dummy image as screen-lock
i3lock -i ~/.config/i3/i3-lock-screen.png -f
